[package]
name = "celestia"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }

[profile.release]
lto = true
strip = "symbols"
